# Versions of cuda dependencies for given cuda versions.
# Note: wrap version in quotes to ensure they're treated as strings.
cuda_deps:
  # List all libcudnn8 versions with `apt list -a libcudnn8`
  libcudnn:
    "12.4": libcudnn9-cuda-12=9.1.0.70-1
    "12.3": libcudnn9-cuda-12=9.0.0.312-1
    "12.1": libcudnn8=8.9.2.26-1+cuda12.1
    "12.0": libcudnn8=8.8.0.121-1+cuda12.0
    "11.8": libcudnn8=8.7.0.84-1+cuda11.8
    "11.7": libcudnn8=8.5.0.96-1+cuda11.7
    "11.2": libcudnn8=8.1.1.33-1+cuda11.2
  libcudnn-dev:
    "12.4": libcudnn9-dev-cuda-12=9.1.0.70-1
    "12.3": libcudnn9-dev-cuda-12=9.0.0.312-1
    "12.1": libcudnn8-dev=8.9.2.26-1+cuda12.1
    "12.0": libcudnn8-dev=8.8.0.121-1+cuda12.0
    "11.8": libcudnn8-dev=8.7.0.84-1+cuda11.8
    "11.7": libcudnn8-dev=8.5.0.96-1+cuda11.7
    "11.2": libcudnn8-dev=8.1.1.33-1+cuda11.2
