# Variables that will be stored in ~/.bashrc and ~/.zshrc files for the release stage.
# They'll be accessible for all processes on the host, also in the development image.
release_env:
  common:
    # Force GCC because clang/bazel has issues.
    CC: gcc-10
    CXX: g++-10
    # CC: "clang-{{ clang_version }}"
    # CXX: "clang++-{{ clang_version }}"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/local/lib"

  tpu:
    ACCELERATOR: tpu
    TPUVM_MODE: 1

  cuda:
    TF_CUDA_COMPUTE_CAPABILITIES: 7.0,7.5,8.0
    XLA_CUDA: 1

# Variables that will be passed to shell environment only for building PyTorch and XLA libs.
build_env:
  common:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/local/lib"
    # Set explicitly to 0 as setup.py defaults this flag to true if unset.
    BUILD_CPP_TESTS: 0
    # Force GCC because clang/bazel has issues.
    CC: gcc-10
    CXX: g++-10
    PYTORCH_BUILD_NUMBER: 1
    TORCH_XLA_VERSION: "{{ package_version }}"
    PYTORCH_BUILD_VERSION: "{{ package_version }}"
    XLA_SANDBOX_BUILD: 1
    BAZEL_REMOTE_CACHE: 1
    SILO_NAME: "cache-silo-{{ arch }}-{{ accelerator }}-{{ clang_version }}"
    DISABLE_XRT: "{{ disable_xrt }}"

  amd64:
    ARCH: amd64

  aarch64:

  cuda:
    TF_CUDA_COMPUTE_CAPABILITIES: 7.0,7.5,8.0
    XLA_CUDA: 1

  tpu:
    ACCELERATOR: tpu
    TPUVM_MODE: 1
    BUNDLE_LIBTPU: "{{ bundle_libtpu }}"
