# Contains lists of pip packages for each stage (build|release) and arch or accelerator.
pip:
  pkgs:
    # Shared between all architectures and accelerators for the build stage.
    build_common:
      - astunparse
      - cffi
      - cloud-tpu-client
      - cmake==3.31.6
      - coverage
      - dataclasses
      - expecttest==0.1.3
      - future
      - git-archive-all
      - google-api-python-client
      - google-cloud-storage
      - hypothesis
      - lark-parser
      - ninja
      - numpy
      - oauth2client
      - pyyaml
      - requests
      - setuptools
      - six
      - tensorboard
      - tensorboardX
      - tqdm
      - typing_extensions
      - sympy
      - yapf==0.40.2  # N.B.: keep in sync with `torchax/dev-requirements.txt`, `.github/workflows/lintercheck.yml`

    build_amd64:
      - mkl
      - mkl-include

    build_aarch64:

    # Shared between all architectures and accelerators for the release stage.
    release_common:
      - numpy
      - pyyaml
      - mkl
      - mkl-include

    release_tpu:
      - torch_xla[tpu]

  # Packages that will be installed with the `--nodeps` flag.
  pkgs_nodeps:
    release_common:
