- name: "Download bazelisk v{{ bazelisk_version }}"
  ansible.builtin.get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v{{ bazelisk_version }}/bazelisk-linux-amd64"
    dest: /usr/local/bin/bazel
    mode: 'u=rxw,g=rw,o=r'
